In [97]:
import pandas as pd

In [98]:
monthly_df=pd.read_csv('C:\\Users\\IJEOMA\\Downloads\\Python-Projects-The-Discovery-of-Handwashing\\Data\\monthly_deaths.csv')

In [99]:
#making a copy of my df
copy_monthly_df=monthly_df.copy()

In [100]:
display(copy_monthly_df)

          date  births  deaths
0   1841-01-01     254      37
1   1841-02-01     239      18
2   1841-03-01     277      12
3   1841-04-01     255       4
4   1841-05-01     255       2
5   1841-06-01     200      10
6   1841-07-01     190      16
7   1841-08-01     222       3
8   1841-09-01     213       4
9   1841-10-01     236      26
10  1841-11-01     235      53
11  1842-01-01     307      64
12  1842-02-01     311      38
13  1842-03-01     264      27
14  1842-04-01     242      26
15  1842-05-01     310      10
16  1842-06-01     273      18
17  1842-07-01     231      48
18  1842-08-01     216      55
19  1842-09-01     223      41
20  1842-10-01     242      71
21  1842-11-01     209      48
22  1842-12-01     239      75
23  1843-01-01     272      52
24  1843-02-01     263      42
25  1843-03-01     266      33
26  1843-04-01     285      34
27  1843-05-01     246      15
28  1843-06-01     196       8
29  1843-07-01     191       1
30  1843-08-01     193       3
31  1843-09-01     221       5
32  1843-10-01     250      44
33  1843-11-01     252      18
34  1843-12-01     236      19
35  1844-01-01     244      37
36  1844-02-01     257      29
37  1844-03-01     276      47
38  1844-04-01     208      36
39  1844-05-01     240      14
40  1844-06-01     224       6
41  1844-07-01     206       9
42  1844-08-01     269      17
43  1844-09-01     245       3
44  1844-10-01     248       8
45  1844-11-01     245      27
46  1844-12-01     256      27
47  1845-01-01     303      23
48  1845-02-01     274      13
49  1845-03-01     292      13
50  1845-04-01     260      11
51  1845-05-01     296      13
52  1845-06-01     280      20
53  1845-07-01     245      15
54  1845-08-01     251       9
55  1845-09-01     237      25
56  1845-10-01     283      42
57  1845-11-01     265      29
58  1845-12-01     267      28
59  1846-01-01     336      45
60  1846-02-01     293      53
61  1846-03-01     311      48
62  1846-04-01     253      48
63  1846-05-01     305      41
64  1846-06-01     266      27
65  1846-07-01     252      33
66  1846-08-01     216      39
67  1846-09-01     271      39
68  1846-10-01     254      38
69  1846-11-01     297      32
70  1846-12-01     298      16
71  1847-01-01     311      10
72  1847-02-01     312       6
73  1847-03-01     305      11
74  1847-04-01     312      57
75  1847-05-01     294      36
76  1847-06-01     268       6
77  1847-07-01     250       3
78  1847-08-01     264       5
79  1847-09-01     262      12
80  1847-10-01     278      11
81  1847-11-01     246      11
82  1847-12-01     273       8
83  1848-01-01     283      10
84  1848-02-01     291       2
85  1848-03-01     276       0
86  1848-04-01     305       2
87  1848-05-01     313       3
88  1848-06-01     264       3
89  1848-07-01     269       1
90  1848-08-01     261       0
91  1848-09-01     312       3
92  1848-10-01     299       7
93  1848-11-01     310       9
94  1848-12-01     373       5
95  1849-01-01     403       9
96  1849-02-01     389      12
97  1849-03-01     406      20

In [101]:
#checking the info of my df
copy_monthly_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 98 entries, 0 to 97
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    98 non-null     object
 1   births  98 non-null     int64
 2   deaths  98 non-null     int64
dtypes: int64(2), object(1)
memory usage: 2.4+ KB

In [102]:
#Adjusting my rows and column display
pd.options.display.max_columns=None
pd.options.display.max_rows=None

In [103]:
copy_monthly_df

          date  births  deaths
0   1841-01-01     254      37
1   1841-02-01     239      18
2   1841-03-01     277      12
3   1841-04-01     255       4
4   1841-05-01     255       2
5   1841-06-01     200      10
6   1841-07-01     190      16
7   1841-08-01     222       3
8   1841-09-01     213       4
9   1841-10-01     236      26
10  1841-11-01     235      53
11  1842-01-01     307      64
12  1842-02-01     311      38
13  1842-03-01     264      27
14  1842-04-01     242      26
15  1842-05-01     310      10
16  1842-06-01     273      18
17  1842-07-01     231      48
18  1842-08-01     216      55
19  1842-09-01     223      41
20  1842-10-01     242      71
21  1842-11-01     209      48
22  1842-12-01     239      75
23  1843-01-01     272      52
24  1843-02-01     263      42
25  1843-03-01     266      33
26  1843-04-01     285      34
27  1843-05-01     246      15
28  1843-06-01     196       8
29  1843-07-01     191       1
30  1843-08-01     193       3
31  1843-09-01     221       5
32  1843-10-01     250      44
33  1843-11-01     252      18
34  1843-12-01     236      19
35  1844-01-01     244      37
36  1844-02-01     257      29
37  1844-03-01     276      47
38  1844-04-01     208      36
39  1844-05-01     240      14
40  1844-06-01     224       6
41  1844-07-01     206       9
42  1844-08-01     269      17
43  1844-09-01     245       3
44  1844-10-01     248       8
45  1844-11-01     245      27
46  1844-12-01     256      27
47  1845-01-01     303      23
48  1845-02-01     274      13
49  1845-03-01     292      13
50  1845-04-01     260      11
51  1845-05-01     296      13
52  1845-06-01     280      20
53  1845-07-01     245      15
54  1845-08-01     251       9
55  1845-09-01     237      25
56  1845-10-01     283      42
57  1845-11-01     265      29
58  1845-12-01     267      28
59  1846-01-01     336      45
60  1846-02-01     293      53
61  1846-03-01     311      48
62  1846-04-01     253      48
63  1846-05-01     305      41
64  1846-06-01     266      27
65  1846-07-01     252      33
66  1846-08-01     216      39
67  1846-09-01     271      39
68  1846-10-01     254      38
69  1846-11-01     297      32
70  1846-12-01     298      16
71  1847-01-01     311      10
72  1847-02-01     312       6
73  1847-03-01     305      11
74  1847-04-01     312      57
75  1847-05-01     294      36
76  1847-06-01     268       6
77  1847-07-01     250       3
78  1847-08-01     264       5
79  1847-09-01     262      12
80  1847-10-01     278      11
81  1847-11-01     246      11
82  1847-12-01     273       8
83  1848-01-01     283      10
84  1848-02-01     291       2
85  1848-03-01     276       0
86  1848-04-01     305       2
87  1848-05-01     313       3
88  1848-06-01     264       3
89  1848-07-01     269       1
90  1848-08-01     261       0
91  1848-09-01     312       3
92  1848-10-01     299       7
93  1848-11-01     310       9
94  1848-12-01     373       5
95  1849-01-01     403       9
96  1849-02-01     389      12
97  1849-03-01     406      20

In [104]:
#Checking the data type of my date column
type(copy_monthly_df['date'])

pandas.core.series.Series

In [105]:
#converting the date column to timestamp
copy_monthly_df['date']=pd.to_datetime(copy_monthly_df['date'], format= '%Y-%m-%d')
print(copy_monthly_df['date'])

0    1841-01-01
1    1841-02-01
2    1841-03-01
3    1841-04-01
4    1841-05-01
5    1841-06-01
6    1841-07-01
7    1841-08-01
8    1841-09-01
9    1841-10-01
10   1841-11-01
11   1842-01-01
12   1842-02-01
13   1842-03-01
14   1842-04-01
15   1842-05-01
16   1842-06-01
17   1842-07-01
18   1842-08-01
19   1842-09-01
20   1842-10-01
21   1842-11-01
22   1842-12-01
23   1843-01-01
24   1843-02-01
25   1843-03-01
26   1843-04-01
27   1843-05-01
28   1843-06-01
29   1843-07-01
30   1843-08-01
31   1843-09-01
32   1843-10-01
33   1843-11-01
34   1843-12-01
35   1844-01-01
36   1844-02-01
37   1844-03-01
38   1844-04-01
39   1844-05-01
40   1844-06-01
41   1844-07-01
42   1844-08-01
43   1844-09-01
44   1844-10-01
45   1844-11-01
46   1844-12-01
47   1845-01-01
48   1845-02-01
49   1845-03-01
50   1845-04-01
51   1845-05-01
52   1845-06-01
53   1845-07-01
54   1845-08-01
55   1845-09-01
56   1845-10-01
57   1845-11-01
58   1845-12-01
59   1846-01-01
60   1846-02-01
61   1846-03-01
62   1846-04-01
63   1846-05-01
64   1846-06-01
65   1846-07-01
66   1846-08-01
67   1846-09-01
68   1846-10-01
69   1846-11-01
70   1846-12-01
71   1847-01-01
72   1847-02-01
73   1847-03-01
74   1847-04-01
75   1847-05-01
76   1847-06-01
77   1847-07-01
78   1847-08-01
79   1847-09-01
80   1847-10-01
81   1847-11-01
82   1847-12-01
83   1848-01-01
84   1848-02-01
85   1848-03-01
86   1848-04-01
87   1848-05-01
88   1848-06-01
89   1848-07-01
90   1848-08-01
91   1848-09-01
92   1848-10-01
93   1848-11-01
94   1848-12-01
95   1849-01-01
96   1849-02-01
97   1849-03-01
Name: date, dtype: datetime64[ns]

In [106]:
type(copy_monthly_df['date'][0])

pandas._libs.tslibs.timestamps.Timestamp

In [107]:
#creating our proportions of death column
copy_monthly_df['Proportions of death']=copy_monthly_df['deaths']/copy_monthly_df['births']
copy_monthly_df

         date  births  deaths  Proportions of death
0  1841-01-01     254      37              0.145669
1  1841-02-01     239      18              0.075314
2  1841-03-01     277      12              0.043321
3  1841-04-01     255       4              0.015686
4  1841-05-01     255       2              0.007843
5  1841-06-01     200      10              0.050000
6  1841-07-01     190      16              0.084211
7  1841-08-01     222       3              0.013514
8  1841-09-01     213       4              0.018779
9  1841-10-01     236      26              0.110169
10 1841-11-01     235      53              0.225532
11 1842-01-01     307      64              0.208469
12 1842-02-01     311      38              0.122186
13 1842-03-01     264      27              0.102273
14 1842-04-01     242      26              0.107438
15 1842-05-01     310      10              0.032258
16 1842-06-01     273      18              0.065934
17 1842-07-01     231      48              0.207792
18 1842-08-01     216      55              0.254630
19 1842-09-01     223      41              0.183857
20 1842-10-01     242      71              0.293388
21 1842-11-01     209      48              0.229665
22 1842-12-01     239      75              0.313808
23 1843-01-01     272      52              0.191176
24 1843-02-01     263      42              0.159696
25 1843-03-01     266      33              0.124060
26 1843-04-01     285      34              0.119298
27 1843-05-01     246      15              0.060976
28 1843-06-01     196       8              0.040816
29 1843-07-01     191       1              0.005236
30 1843-08-01     193       3              0.015544
31 1843-09-01     221       5              0.022624
32 1843-10-01     250      44              0.176000
33 1843-11-01     252      18              0.071429
34 1843-12-01     236      19              0.080508
35 1844-01-01     244      37              0.151639
36 1844-02-01     257      29              0.112840
37 1844-03-01     276      47              0.170290
38 1844-04-01     208      36              0.173077
39 1844-05-01     240      14              0.058333
40 1844-06-01     224       6              0.026786
41 1844-07-01     206       9              0.043689
42 1844-08-01     269      17              0.063197
43 1844-09-01     245       3              0.012245
44 1844-10-01     248       8              0.032258
45 1844-11-01     245      27              0.110204
46 1844-12-01     256      27              0.105469
47 1845-01-01     303      23              0.075908
48 1845-02-01     274      13              0.047445
49 1845-03-01     292      13              0.044521
50 1845-04-01     260      11              0.042308
51 1845-05-01     296      13              0.043919
52 1845-06-01     280      20              0.071429
53 1845-07-01     245      15              0.061224
54 1845-08-01     251       9              0.035857
55 1845-09-01     237      25              0.105485
56 1845-10-01     283      42              0.148410
57 1845-11-01     265      29              0.109434
58 1845-12-01     267      28              0.104869
59 1846-01-01     336      45              0.133929
60 1846-02-01     293      53              0.180887
61 1846-03-01     311      48              0.154341
62 1846-04-01     253      48              0.189723
63 1846-05-01     305      41              0.134426
64 1846-06-01     266      27              0.101504
65 1846-07-01     252      33              0.130952
66 1846-08-01     216      39              0.180556
67 1846-09-01     271      39              0.143911
68 1846-10-01     254      38              0.149606
69 1846-11-01     297      32              0.107744
70 1846-12-01     298      16              0.053691
71 1847-01-01     311      10              0.032154
72 1847-02-01     312       6              0.019231
73 1847-03-01     305      11              0.036066
74 1847-04-01     312      57              0.182692
75 1847-05-01     294      36              0.122449
76 1847-06-01     268       6              0.022388
77 1847-07-01     250       3              0.012000
78 1847-08-01     264       5              0.018939
79 1847-09-01     262      12              0.045802
80 1847-10-01     278      11              0.039568
81 1847-11-01     246      11              0.044715
82 1847-12-01     273       8              0.029304
83 1848-01-01     283      10              0.035336
84 1848-02-01     291       2              0.006873
85 1848-03-01     276       0              0.000000
86 1848-04-01     305       2              0.006557
87 1848-05-01     313       3              0.009585
88 1848-06-01     264       3              0.011364
89 1848-07-01     269       1              0.003717
90 1848-08-01     261       0              0.000000
91 1848-09-01     312       3              0.009615
92 1848-10-01     299       7              0.023411
93 1848-11-01     310       9              0.029032
94 1848-12-01     373       5              0.013405
95 1849-01-01     403       9              0.022333
96 1849-02-01     389      12              0.030848
97 1849-03-01     406      20              0.049261

#Extracting the month and year values and creating seperate columns for them

In [108]:
copy_monthly_df.shape

(98, 4)

In [109]:
month_values=[]
month_values

[]

In [110]:
for x in range(98):
    month_values.append(copy_monthly_df['date'][x].month)

In [111]:
month_values

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 1,
 2,
 3]

In [112]:
Year_values=[]
Year_values

[]

In [113]:
for x in range(98):
    Year_values.append(copy_monthly_df['date'][x].year)
display(Year_values)

[1841,
 1841,
 1841,
 1841,
 1841,
 1841,
 1841,
 1841,
 1841,
 1841,
 1841,
 1842,
 1842,
 1842,
 1842,
 1842,
 1842,
 1842,
 1842,
 1842,
 1842,
 1842,
 1842,
 1843,
 1843,
 1843,
 1843,
 1843,
 1843,
 1843,
 1843,
 1843,
 1843,
 1843,
 1843,
 1844,
 1844,
 1844,
 1844,
 1844,
 1844,
 1844,
 1844,
 1844,
 1844,
 1844,
 1844,
 1845,
 1845,
 1845,
 1845,
 1845,
 1845,
 1845,
 1845,
 1845,
 1845,
 1845,
 1845,
 1846,
 1846,
 1846,
 1846,
 1846,
 1846,
 1846,
 1846,
 1846,
 1846,
 1846,
 1846,
 1847,
 1847,
 1847,
 1847,
 1847,
 1847,
 1847,
 1847,
 1847,
 1847,
 1847,
 1847,
 1848,
 1848,
 1848,
 1848,
 1848,
 1848,
 1848,
 1848,
 1848,
 1848,
 1848,
 1848,
 1849,
 1849,
 1849]

In [114]:
copy_monthly_df

         date  births  deaths  Proportions of death
0  1841-01-01     254      37              0.145669
1  1841-02-01     239      18              0.075314
2  1841-03-01     277      12              0.043321
3  1841-04-01     255       4              0.015686
4  1841-05-01     255       2              0.007843
5  1841-06-01     200      10              0.050000
6  1841-07-01     190      16              0.084211
7  1841-08-01     222       3              0.013514
8  1841-09-01     213       4              0.018779
9  1841-10-01     236      26              0.110169
10 1841-11-01     235      53              0.225532
11 1842-01-01     307      64              0.208469
12 1842-02-01     311      38              0.122186
13 1842-03-01     264      27              0.102273
14 1842-04-01     242      26              0.107438
15 1842-05-01     310      10              0.032258
16 1842-06-01     273      18              0.065934
17 1842-07-01     231      48              0.207792
18 1842-08-01     216      55              0.254630
19 1842-09-01     223      41              0.183857
20 1842-10-01     242      71              0.293388
21 1842-11-01     209      48              0.229665
22 1842-12-01     239      75              0.313808
23 1843-01-01     272      52              0.191176
24 1843-02-01     263      42              0.159696
25 1843-03-01     266      33              0.124060
26 1843-04-01     285      34              0.119298
27 1843-05-01     246      15              0.060976
28 1843-06-01     196       8              0.040816
29 1843-07-01     191       1              0.005236
30 1843-08-01     193       3              0.015544
31 1843-09-01     221       5              0.022624
32 1843-10-01     250      44              0.176000
33 1843-11-01     252      18              0.071429
34 1843-12-01     236      19              0.080508
35 1844-01-01     244      37              0.151639
36 1844-02-01     257      29              0.112840
37 1844-03-01     276      47              0.170290
38 1844-04-01     208      36              0.173077
39 1844-05-01     240      14              0.058333
40 1844-06-01     224       6              0.026786
41 1844-07-01     206       9              0.043689
42 1844-08-01     269      17              0.063197
43 1844-09-01     245       3              0.012245
44 1844-10-01     248       8              0.032258
45 1844-11-01     245      27              0.110204
46 1844-12-01     256      27              0.105469
47 1845-01-01     303      23              0.075908
48 1845-02-01     274      13              0.047445
49 1845-03-01     292      13              0.044521
50 1845-04-01     260      11              0.042308
51 1845-05-01     296      13              0.043919
52 1845-06-01     280      20              0.071429
53 1845-07-01     245      15              0.061224
54 1845-08-01     251       9              0.035857
55 1845-09-01     237      25              0.105485
56 1845-10-01     283      42              0.148410
57 1845-11-01     265      29              0.109434
58 1845-12-01     267      28              0.104869
59 1846-01-01     336      45              0.133929
60 1846-02-01     293      53              0.180887
61 1846-03-01     311      48              0.154341
62 1846-04-01     253      48              0.189723
63 1846-05-01     305      41              0.134426
64 1846-06-01     266      27              0.101504
65 1846-07-01     252      33              0.130952
66 1846-08-01     216      39              0.180556
67 1846-09-01     271      39              0.143911
68 1846-10-01     254      38              0.149606
69 1846-11-01     297      32              0.107744
70 1846-12-01     298      16              0.053691
71 1847-01-01     311      10              0.032154
72 1847-02-01     312       6              0.019231
73 1847-03-01     305      11              0.036066
74 1847-04-01     312      57              0.182692
75 1847-05-01     294      36              0.122449
76 1847-06-01     268       6              0.022388
77 1847-07-01     250       3              0.012000
78 1847-08-01     264       5              0.018939
79 1847-09-01     262      12              0.045802
80 1847-10-01     278      11              0.039568
81 1847-11-01     246      11              0.044715
82 1847-12-01     273       8              0.029304
83 1848-01-01     283      10              0.035336
84 1848-02-01     291       2              0.006873
85 1848-03-01     276       0              0.000000
86 1848-04-01     305       2              0.006557
87 1848-05-01     313       3              0.009585
88 1848-06-01     264       3              0.011364
89 1848-07-01     269       1              0.003717
90 1848-08-01     261       0              0.000000
91 1848-09-01     312       3              0.009615
92 1848-10-01     299       7              0.023411
93 1848-11-01     310       9              0.029032
94 1848-12-01     373       5              0.013405
95 1849-01-01     403       9              0.022333
96 1849-02-01     389      12              0.030848
97 1849-03-01     406      20              0.049261

In [115]:
month_values

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 1,
 2,
 3]

In [116]:
#Creating and adding the month_value column to my df
copy_monthly_df['Month_v']=month_values

In [117]:
copy_monthly_df

         date  births  deaths  Proportions of death  Month_v
0  1841-01-01     254      37              0.145669        1
1  1841-02-01     239      18              0.075314        2
2  1841-03-01     277      12              0.043321        3
3  1841-04-01     255       4              0.015686        4
4  1841-05-01     255       2              0.007843        5
5  1841-06-01     200      10              0.050000        6
6  1841-07-01     190      16              0.084211        7
7  1841-08-01     222       3              0.013514        8
8  1841-09-01     213       4              0.018779        9
9  1841-10-01     236      26              0.110169       10
10 1841-11-01     235      53              0.225532       11
11 1842-01-01     307      64              0.208469        1
12 1842-02-01     311      38              0.122186        2
13 1842-03-01     264      27              0.102273        3
14 1842-04-01     242      26              0.107438        4
15 1842-05-01     310      10              0.032258        5
16 1842-06-01     273      18              0.065934        6
17 1842-07-01     231      48              0.207792        7
18 1842-08-01     216      55              0.254630        8
19 1842-09-01     223      41              0.183857        9
20 1842-10-01     242      71              0.293388       10
21 1842-11-01     209      48              0.229665       11
22 1842-12-01     239      75              0.313808       12
23 1843-01-01     272      52              0.191176        1
24 1843-02-01     263      42              0.159696        2
25 1843-03-01     266      33              0.124060        3
26 1843-04-01     285      34              0.119298        4
27 1843-05-01     246      15              0.060976        5
28 1843-06-01     196       8              0.040816        6
29 1843-07-01     191       1              0.005236        7
30 1843-08-01     193       3              0.015544        8
31 1843-09-01     221       5              0.022624        9
32 1843-10-01     250      44              0.176000       10
33 1843-11-01     252      18              0.071429       11
34 1843-12-01     236      19              0.080508       12
35 1844-01-01     244      37              0.151639        1
36 1844-02-01     257      29              0.112840        2
37 1844-03-01     276      47              0.170290        3
38 1844-04-01     208      36              0.173077        4
39 1844-05-01     240      14              0.058333        5
40 1844-06-01     224       6              0.026786        6
41 1844-07-01     206       9              0.043689        7
42 1844-08-01     269      17              0.063197        8
43 1844-09-01     245       3              0.012245        9
44 1844-10-01     248       8              0.032258       10
45 1844-11-01     245      27              0.110204       11
46 1844-12-01     256      27              0.105469       12
47 1845-01-01     303      23              0.075908        1
48 1845-02-01     274      13              0.047445        2
49 1845-03-01     292      13              0.044521        3
50 1845-04-01     260      11              0.042308        4
51 1845-05-01     296      13              0.043919        5
52 1845-06-01     280      20              0.071429        6
53 1845-07-01     245      15              0.061224        7
54 1845-08-01     251       9              0.035857        8
55 1845-09-01     237      25              0.105485        9
56 1845-10-01     283      42              0.148410       10
57 1845-11-01     265      29              0.109434       11
58 1845-12-01     267      28              0.104869       12
59 1846-01-01     336      45              0.133929        1
60 1846-02-01     293      53              0.180887        2
61 1846-03-01     311      48              0.154341        3
62 1846-04-01     253      48              0.189723        4
63 1846-05-01     305      41              0.134426        5
64 1846-06-01     266      27              0.101504        6
65 1846-07-01     252      33              0.130952        7
66 1846-08-01     216      39              0.180556        8
67 1846-09-01     271      39              0.143911        9
68 1846-10-01     254      38              0.149606       10
69 1846-11-01     297      32              0.107744       11
70 1846-12-01     298      16              0.053691       12
71 1847-01-01     311      10              0.032154        1
72 1847-02-01     312       6              0.019231        2
73 1847-03-01     305      11              0.036066        3
74 1847-04-01     312      57              0.182692        4
75 1847-05-01     294      36              0.122449        5
76 1847-06-01     268       6              0.022388        6
77 1847-07-01     250       3              0.012000        7
78 1847-08-01     264       5              0.018939        8
79 1847-09-01     262      12              0.045802        9
80 1847-10-01     278      11              0.039568       10
81 1847-11-01     246      11              0.044715       11
82 1847-12-01     273       8              0.029304       12
83 1848-01-01     283      10              0.035336        1
84 1848-02-01     291       2              0.006873        2
85 1848-03-01     276       0              0.000000        3
86 1848-04-01     305       2              0.006557        4
87 1848-05-01     313       3              0.009585        5
88 1848-06-01     264       3              0.011364        6
89 1848-07-01     269       1              0.003717        7
90 1848-08-01     261       0              0.000000        8
91 1848-09-01     312       3              0.009615        9
92 1848-10-01     299       7              0.023411       10
93 1848-11-01     310       9              0.029032       11
94 1848-12-01     373       5              0.013405       12
95 1849-01-01     403       9              0.022333        1
96 1849-02-01     389      12              0.030848        2
97 1849-03-01     406      20              0.049261        3

In [118]:
#creating and adding the year value column to my df
copy_monthly_df['Year_v']=Year_values
copy_monthly_df

         date  births  deaths  Proportions of death  Month_v  Year_v
0  1841-01-01     254      37              0.145669        1    1841
1  1841-02-01     239      18              0.075314        2    1841
2  1841-03-01     277      12              0.043321        3    1841
3  1841-04-01     255       4              0.015686        4    1841
4  1841-05-01     255       2              0.007843        5    1841
5  1841-06-01     200      10              0.050000        6    1841
6  1841-07-01     190      16              0.084211        7    1841
7  1841-08-01     222       3              0.013514        8    1841
8  1841-09-01     213       4              0.018779        9    1841
9  1841-10-01     236      26              0.110169       10    1841
10 1841-11-01     235      53              0.225532       11    1841
11 1842-01-01     307      64              0.208469        1    1842
12 1842-02-01     311      38              0.122186        2    1842
13 1842-03-01     264      27              0.102273        3    1842
14 1842-04-01     242      26              0.107438        4    1842
15 1842-05-01     310      10              0.032258        5    1842
16 1842-06-01     273      18              0.065934        6    1842
17 1842-07-01     231      48              0.207792        7    1842
18 1842-08-01     216      55              0.254630        8    1842
19 1842-09-01     223      41              0.183857        9    1842
20 1842-10-01     242      71              0.293388       10    1842
21 1842-11-01     209      48              0.229665       11    1842
22 1842-12-01     239      75              0.313808       12    1842
23 1843-01-01     272      52              0.191176        1    1843
24 1843-02-01     263      42              0.159696        2    1843
25 1843-03-01     266      33              0.124060        3    1843
26 1843-04-01     285      34              0.119298        4    1843
27 1843-05-01     246      15              0.060976        5    1843
28 1843-06-01     196       8              0.040816        6    1843
29 1843-07-01     191       1              0.005236        7    1843
30 1843-08-01     193       3              0.015544        8    1843
31 1843-09-01     221       5              0.022624        9    1843
32 1843-10-01     250      44              0.176000       10    1843
33 1843-11-01     252      18              0.071429       11    1843
34 1843-12-01     236      19              0.080508       12    1843
35 1844-01-01     244      37              0.151639        1    1844
36 1844-02-01     257      29              0.112840        2    1844
37 1844-03-01     276      47              0.170290        3    1844
38 1844-04-01     208      36              0.173077        4    1844
39 1844-05-01     240      14              0.058333        5    1844
40 1844-06-01     224       6              0.026786        6    1844
41 1844-07-01     206       9              0.043689        7    1844
42 1844-08-01     269      17              0.063197        8    1844
43 1844-09-01     245       3              0.012245        9    1844
44 1844-10-01     248       8              0.032258       10    1844
45 1844-11-01     245      27              0.110204       11    1844
46 1844-12-01     256      27              0.105469       12    1844
47 1845-01-01     303      23              0.075908        1    1845
48 1845-02-01     274      13              0.047445        2    1845
49 1845-03-01     292      13              0.044521        3    1845
50 1845-04-01     260      11              0.042308        4    1845
51 1845-05-01     296      13              0.043919        5    1845
52 1845-06-01     280      20              0.071429        6    1845
53 1845-07-01     245      15              0.061224        7    1845
54 1845-08-01     251       9              0.035857        8    1845
55 1845-09-01     237      25              0.105485        9    1845
56 1845-10-01     283      42              0.148410       10    1845
57 1845-11-01     265      29              0.109434       11    1845
58 1845-12-01     267      28              0.104869       12    1845
59 1846-01-01     336      45              0.133929        1    1846
60 1846-02-01     293      53              0.180887        2    1846
61 1846-03-01     311      48              0.154341        3    1846
62 1846-04-01     253      48              0.189723        4    1846
63 1846-05-01     305      41              0.134426        5    1846
64 1846-06-01     266      27              0.101504        6    1846
65 1846-07-01     252      33              0.130952        7    1846
66 1846-08-01     216      39              0.180556        8    1846
67 1846-09-01     271      39              0.143911        9    1846
68 1846-10-01     254      38              0.149606       10    1846
69 1846-11-01     297      32              0.107744       11    1846
70 1846-12-01     298      16              0.053691       12    1846
71 1847-01-01     311      10              0.032154        1    1847
72 1847-02-01     312       6              0.019231        2    1847
73 1847-03-01     305      11              0.036066        3    1847
74 1847-04-01     312      57              0.182692        4    1847
75 1847-05-01     294      36              0.122449        5    1847
76 1847-06-01     268       6              0.022388        6    1847
77 1847-07-01     250       3              0.012000        7    1847
78 1847-08-01     264       5              0.018939        8    1847
79 1847-09-01     262      12              0.045802        9    1847
80 1847-10-01     278      11              0.039568       10    1847
81 1847-11-01     246      11              0.044715       11    1847
82 1847-12-01     273       8              0.029304       12    1847
83 1848-01-01     283      10              0.035336        1    1848
84 1848-02-01     291       2              0.006873        2    1848
85 1848-03-01     276       0              0.000000        3    1848
86 1848-04-01     305       2              0.006557        4    1848
87 1848-05-01     313       3              0.009585        5    1848
88 1848-06-01     264       3              0.011364        6    1848
89 1848-07-01     269       1              0.003717        7    1848
90 1848-08-01     261       0              0.000000        8    1848
91 1848-09-01     312       3              0.009615        9    1848
92 1848-10-01     299       7              0.023411       10    1848
93 1848-11-01     310       9              0.029032       11    1848
94 1848-12-01     373       5              0.013405       12    1848
95 1849-01-01     403       9              0.022333        1    1849
96 1849-02-01     389      12              0.030848        2    1849
97 1849-03-01     406      20              0.049261        3    1849

In [119]:
#dropping the date column
copy_monthly_df=copy_monthly_df.drop(['date'], axis=1)
copy_monthly_df

    births  deaths  Proportions of death  Month_v  Year_v
0      254      37              0.145669        1    1841
1      239      18              0.075314        2    1841
2      277      12              0.043321        3    1841
3      255       4              0.015686        4    1841
4      255       2              0.007843        5    1841
5      200      10              0.050000        6    1841
6      190      16              0.084211        7    1841
7      222       3              0.013514        8    1841
8      213       4              0.018779        9    1841
9      236      26              0.110169       10    1841
10     235      53              0.225532       11    1841
11     307      64              0.208469        1    1842
12     311      38              0.122186        2    1842
13     264      27              0.102273        3    1842
14     242      26              0.107438        4    1842
15     310      10              0.032258        5    1842
16     273      18              0.065934        6    1842
17     231      48              0.207792        7    1842
18     216      55              0.254630        8    1842
19     223      41              0.183857        9    1842
20     242      71              0.293388       10    1842
21     209      48              0.229665       11    1842
22     239      75              0.313808       12    1842
23     272      52              0.191176        1    1843
24     263      42              0.159696        2    1843
25     266      33              0.124060        3    1843
26     285      34              0.119298        4    1843
27     246      15              0.060976        5    1843
28     196       8              0.040816        6    1843
29     191       1              0.005236        7    1843
30     193       3              0.015544        8    1843
31     221       5              0.022624        9    1843
32     250      44              0.176000       10    1843
33     252      18              0.071429       11    1843
34     236      19              0.080508       12    1843
35     244      37              0.151639        1    1844
36     257      29              0.112840        2    1844
37     276      47              0.170290        3    1844
38     208      36              0.173077        4    1844
39     240      14              0.058333        5    1844
40     224       6              0.026786        6    1844
41     206       9              0.043689        7    1844
42     269      17              0.063197        8    1844
43     245       3              0.012245        9    1844
44     248       8              0.032258       10    1844
45     245      27              0.110204       11    1844
46     256      27              0.105469       12    1844
47     303      23              0.075908        1    1845
48     274      13              0.047445        2    1845
49     292      13              0.044521        3    1845
50     260      11              0.042308        4    1845
51     296      13              0.043919        5    1845
52     280      20              0.071429        6    1845
53     245      15              0.061224        7    1845
54     251       9              0.035857        8    1845
55     237      25              0.105485        9    1845
56     283      42              0.148410       10    1845
57     265      29              0.109434       11    1845
58     267      28              0.104869       12    1845
59     336      45              0.133929        1    1846
60     293      53              0.180887        2    1846
61     311      48              0.154341        3    1846
62     253      48              0.189723        4    1846
63     305      41              0.134426        5    1846
64     266      27              0.101504        6    1846
65     252      33              0.130952        7    1846
66     216      39              0.180556        8    1846
67     271      39              0.143911        9    1846
68     254      38              0.149606       10    1846
69     297      32              0.107744       11    1846
70     298      16              0.053691       12    1846
71     311      10              0.032154        1    1847
72     312       6              0.019231        2    1847
73     305      11              0.036066        3    1847
74     312      57              0.182692        4    1847
75     294      36              0.122449        5    1847
76     268       6              0.022388        6    1847
77     250       3              0.012000        7    1847
78     264       5              0.018939        8    1847
79     262      12              0.045802        9    1847
80     278      11              0.039568       10    1847
81     246      11              0.044715       11    1847
82     273       8              0.029304       12    1847
83     283      10              0.035336        1    1848
84     291       2              0.006873        2    1848
85     276       0              0.000000        3    1848
86     305       2              0.006557        4    1848
87     313       3              0.009585        5    1848
88     264       3              0.011364        6    1848
89     269       1              0.003717        7    1848
90     261       0              0.000000        8    1848
91     312       3              0.009615        9    1848
92     299       7              0.023411       10    1848
93     310       9              0.029032       11    1848
94     373       5              0.013405       12    1848
95     403       9              0.022333        1    1849
96     389      12              0.030848        2    1849
97     406      20              0.049261        3    1849

In [120]:
#reordering the columns of my data frame
copy_monthly_df.columns.values

array(['births', 'deaths', 'Proportions of death', 'Month_v', 'Year_v'],
      dtype=object)

In [121]:
column_names_reordered=[]

In [122]:
column_names_reordered=['Year_v','Month_v','births', 'deaths', 'Proportions of death']

In [123]:
copy_monthly_df=copy_monthly_df[column_names_reordered]

In [124]:
copy_monthly_df

    Year_v  Month_v  births  deaths  Proportions of death
0     1841        1     254      37              0.145669
1     1841        2     239      18              0.075314
2     1841        3     277      12              0.043321
3     1841        4     255       4              0.015686
4     1841        5     255       2              0.007843
5     1841        6     200      10              0.050000
6     1841        7     190      16              0.084211
7     1841        8     222       3              0.013514
8     1841        9     213       4              0.018779
9     1841       10     236      26              0.110169
10    1841       11     235      53              0.225532
11    1842        1     307      64              0.208469
12    1842        2     311      38              0.122186
13    1842        3     264      27              0.102273
14    1842        4     242      26              0.107438
15    1842        5     310      10              0.032258
16    1842        6     273      18              0.065934
17    1842        7     231      48              0.207792
18    1842        8     216      55              0.254630
19    1842        9     223      41              0.183857
20    1842       10     242      71              0.293388
21    1842       11     209      48              0.229665
22    1842       12     239      75              0.313808
23    1843        1     272      52              0.191176
24    1843        2     263      42              0.159696
25    1843        3     266      33              0.124060
26    1843        4     285      34              0.119298
27    1843        5     246      15              0.060976
28    1843        6     196       8              0.040816
29    1843        7     191       1              0.005236
30    1843        8     193       3              0.015544
31    1843        9     221       5              0.022624
32    1843       10     250      44              0.176000
33    1843       11     252      18              0.071429
34    1843       12     236      19              0.080508
35    1844        1     244      37              0.151639
36    1844        2     257      29              0.112840
37    1844        3     276      47              0.170290
38    1844        4     208      36              0.173077
39    1844        5     240      14              0.058333
40    1844        6     224       6              0.026786
41    1844        7     206       9              0.043689
42    1844        8     269      17              0.063197
43    1844        9     245       3              0.012245
44    1844       10     248       8              0.032258
45    1844       11     245      27              0.110204
46    1844       12     256      27              0.105469
47    1845        1     303      23              0.075908
48    1845        2     274      13              0.047445
49    1845        3     292      13              0.044521
50    1845        4     260      11              0.042308
51    1845        5     296      13              0.043919
52    1845        6     280      20              0.071429
53    1845        7     245      15              0.061224
54    1845        8     251       9              0.035857
55    1845        9     237      25              0.105485
56    1845       10     283      42              0.148410
57    1845       11     265      29              0.109434
58    1845       12     267      28              0.104869
59    1846        1     336      45              0.133929
60    1846        2     293      53              0.180887
61    1846        3     311      48              0.154341
62    1846        4     253      48              0.189723
63    1846        5     305      41              0.134426
64    1846        6     266      27              0.101504
65    1846        7     252      33              0.130952
66    1846        8     216      39              0.180556
67    1846        9     271      39              0.143911
68    1846       10     254      38              0.149606
69    1846       11     297      32              0.107744
70    1846       12     298      16              0.053691
71    1847        1     311      10              0.032154
72    1847        2     312       6              0.019231
73    1847        3     305      11              0.036066
74    1847        4     312      57              0.182692
75    1847        5     294      36              0.122449
76    1847        6     268       6              0.022388
77    1847        7     250       3              0.012000
78    1847        8     264       5              0.018939
79    1847        9     262      12              0.045802
80    1847       10     278      11              0.039568
81    1847       11     246      11              0.044715
82    1847       12     273       8              0.029304
83    1848        1     283      10              0.035336
84    1848        2     291       2              0.006873
85    1848        3     276       0              0.000000
86    1848        4     305       2              0.006557
87    1848        5     313       3              0.009585
88    1848        6     264       3              0.011364
89    1848        7     269       1              0.003717
90    1848        8     261       0              0.000000
91    1848        9     312       3              0.009615
92    1848       10     299       7              0.023411
93    1848       11     310       9              0.029032
94    1848       12     373       5              0.013405
95    1849        1     403       9              0.022333
96    1849        2     389      12              0.030848
97    1849        3     406      20              0.049261

Dr. Semmelweis told the doctors to start washing their hands in the summer of 1847 that is June 1847, so we will split the data into pre hand washing and post hand washing in order to be able to compare the death proportions from both periods.

In [125]:
#splitting my data frame
Before_handwashing=copy_monthly_df.iloc[:76]
After_handwashig=copy_monthly_df.iloc[76:]

In [126]:
Before_handwashing

    Year_v  Month_v  births  deaths  Proportions of death
0     1841        1     254      37              0.145669
1     1841        2     239      18              0.075314
2     1841        3     277      12              0.043321
3     1841        4     255       4              0.015686
4     1841        5     255       2              0.007843
5     1841        6     200      10              0.050000
6     1841        7     190      16              0.084211
7     1841        8     222       3              0.013514
8     1841        9     213       4              0.018779
9     1841       10     236      26              0.110169
10    1841       11     235      53              0.225532
11    1842        1     307      64              0.208469
12    1842        2     311      38              0.122186
13    1842        3     264      27              0.102273
14    1842        4     242      26              0.107438
15    1842        5     310      10              0.032258
16    1842        6     273      18              0.065934
17    1842        7     231      48              0.207792
18    1842        8     216      55              0.254630
19    1842        9     223      41              0.183857
20    1842       10     242      71              0.293388
21    1842       11     209      48              0.229665
22    1842       12     239      75              0.313808
23    1843        1     272      52              0.191176
24    1843        2     263      42              0.159696
25    1843        3     266      33              0.124060
26    1843        4     285      34              0.119298
27    1843        5     246      15              0.060976
28    1843        6     196       8              0.040816
29    1843        7     191       1              0.005236
30    1843        8     193       3              0.015544
31    1843        9     221       5              0.022624
32    1843       10     250      44              0.176000
33    1843       11     252      18              0.071429
34    1843       12     236      19              0.080508
35    1844        1     244      37              0.151639
36    1844        2     257      29              0.112840
37    1844        3     276      47              0.170290
38    1844        4     208      36              0.173077
39    1844        5     240      14              0.058333
40    1844        6     224       6              0.026786
41    1844        7     206       9              0.043689
42    1844        8     269      17              0.063197
43    1844        9     245       3              0.012245
44    1844       10     248       8              0.032258
45    1844       11     245      27              0.110204
46    1844       12     256      27              0.105469
47    1845        1     303      23              0.075908
48    1845        2     274      13              0.047445
49    1845        3     292      13              0.044521
50    1845        4     260      11              0.042308
51    1845        5     296      13              0.043919
52    1845        6     280      20              0.071429
53    1845        7     245      15              0.061224
54    1845        8     251       9              0.035857
55    1845        9     237      25              0.105485
56    1845       10     283      42              0.148410
57    1845       11     265      29              0.109434
58    1845       12     267      28              0.104869
59    1846        1     336      45              0.133929
60    1846        2     293      53              0.180887
61    1846        3     311      48              0.154341
62    1846        4     253      48              0.189723
63    1846        5     305      41              0.134426
64    1846        6     266      27              0.101504
65    1846        7     252      33              0.130952
66    1846        8     216      39              0.180556
67    1846        9     271      39              0.143911
68    1846       10     254      38              0.149606
69    1846       11     297      32              0.107744
70    1846       12     298      16              0.053691
71    1847        1     311      10              0.032154
72    1847        2     312       6              0.019231
73    1847        3     305      11              0.036066
74    1847        4     312      57              0.182692
75    1847        5     294      36              0.122449

In [127]:
After_handwashig

    Year_v  Month_v  births  deaths  Proportions of death
76    1847        6     268       6              0.022388
77    1847        7     250       3              0.012000
78    1847        8     264       5              0.018939
79    1847        9     262      12              0.045802
80    1847       10     278      11              0.039568
81    1847       11     246      11              0.044715
82    1847       12     273       8              0.029304
83    1848        1     283      10              0.035336
84    1848        2     291       2              0.006873
85    1848        3     276       0              0.000000
86    1848        4     305       2              0.006557
87    1848        5     313       3              0.009585
88    1848        6     264       3              0.011364
89    1848        7     269       1              0.003717
90    1848        8     261       0              0.000000
91    1848        9     312       3              0.009615
92    1848       10     299       7              0.023411
93    1848       11     310       9              0.029032
94    1848       12     373       5              0.013405
95    1849        1     403       9              0.022333
96    1849        2     389      12              0.030848
97    1849        3     406      20              0.049261

In [128]:
#Calculating the mean of both periods for comparison
Before_proportions=Before_handwashing['Proportions of death']
After_proportions=After_handwashig['Proportions of death']

In [129]:
Before_proportions.mean()

0.10504998260908793

In [130]:
After_proportions.mean()

0.021093375097254535

From the mean calculations above it is obvious that the average proportions of death reduced to 2% from 10% that is the average recorded before handwashing was introduced.

In [131]:
display(Before_handwashing)

    Year_v  Month_v  births  deaths  Proportions of death
0     1841        1     254      37              0.145669
1     1841        2     239      18              0.075314
2     1841        3     277      12              0.043321
3     1841        4     255       4              0.015686
4     1841        5     255       2              0.007843
5     1841        6     200      10              0.050000
6     1841        7     190      16              0.084211
7     1841        8     222       3              0.013514
8     1841        9     213       4              0.018779
9     1841       10     236      26              0.110169
10    1841       11     235      53              0.225532
11    1842        1     307      64              0.208469
12    1842        2     311      38              0.122186
13    1842        3     264      27              0.102273
14    1842        4     242      26              0.107438
15    1842        5     310      10              0.032258
16    1842        6     273      18              0.065934
17    1842        7     231      48              0.207792
18    1842        8     216      55              0.254630
19    1842        9     223      41              0.183857
20    1842       10     242      71              0.293388
21    1842       11     209      48              0.229665
22    1842       12     239      75              0.313808
23    1843        1     272      52              0.191176
24    1843        2     263      42              0.159696
25    1843        3     266      33              0.124060
26    1843        4     285      34              0.119298
27    1843        5     246      15              0.060976
28    1843        6     196       8              0.040816
29    1843        7     191       1              0.005236
30    1843        8     193       3              0.015544
31    1843        9     221       5              0.022624
32    1843       10     250      44              0.176000
33    1843       11     252      18              0.071429
34    1843       12     236      19              0.080508
35    1844        1     244      37              0.151639
36    1844        2     257      29              0.112840
37    1844        3     276      47              0.170290
38    1844        4     208      36              0.173077
39    1844        5     240      14              0.058333
40    1844        6     224       6              0.026786
41    1844        7     206       9              0.043689
42    1844        8     269      17              0.063197
43    1844        9     245       3              0.012245
44    1844       10     248       8              0.032258
45    1844       11     245      27              0.110204
46    1844       12     256      27              0.105469
47    1845        1     303      23              0.075908
48    1845        2     274      13              0.047445
49    1845        3     292      13              0.044521
50    1845        4     260      11              0.042308
51    1845        5     296      13              0.043919
52    1845        6     280      20              0.071429
53    1845        7     245      15              0.061224
54    1845        8     251       9              0.035857
55    1845        9     237      25              0.105485
56    1845       10     283      42              0.148410
57    1845       11     265      29              0.109434
58    1845       12     267      28              0.104869
59    1846        1     336      45              0.133929
60    1846        2     293      53              0.180887
61    1846        3     311      48              0.154341
62    1846        4     253      48              0.189723
63    1846        5     305      41              0.134426
64    1846        6     266      27              0.101504
65    1846        7     252      33              0.130952
66    1846        8     216      39              0.180556
67    1846        9     271      39              0.143911
68    1846       10     254      38              0.149606
69    1846       11     297      32              0.107744
70    1846       12     298      16              0.053691
71    1847        1     311      10              0.032154
72    1847        2     312       6              0.019231
73    1847        3     305      11              0.036066
74    1847        4     312      57              0.182692
75    1847        5     294      36              0.122449

In [132]:
display(After_handwashig)

    Year_v  Month_v  births  deaths  Proportions of death
76    1847        6     268       6              0.022388
77    1847        7     250       3              0.012000
78    1847        8     264       5              0.018939
79    1847        9     262      12              0.045802
80    1847       10     278      11              0.039568
81    1847       11     246      11              0.044715
82    1847       12     273       8              0.029304
83    1848        1     283      10              0.035336
84    1848        2     291       2              0.006873
85    1848        3     276       0              0.000000
86    1848        4     305       2              0.006557
87    1848        5     313       3              0.009585
88    1848        6     264       3              0.011364
89    1848        7     269       1              0.003717
90    1848        8     261       0              0.000000
91    1848        9     312       3              0.009615
92    1848       10     299       7              0.023411
93    1848       11     310       9              0.029032
94    1848       12     373       5              0.013405
95    1849        1     403       9              0.022333
96    1849        2     389      12              0.030848
97    1849        3     406      20              0.049261

Moving my data to mysql. I did this in two sets because I will visualize them separately and then put together in dashboard in tableau for comparison and for us to easily draw insights from comparing both visualizations

In [133]:
import pymysql

In [134]:
conn=pymysql.connect(database='before_handwashing_analysis', user='root', password='22101989')

In [135]:
cursor=conn.cursor()

In [136]:
cursor.execute('select*from before_handwashing_analysis')

228

In [137]:
#creating my insert_query variable that i will use to send my data from jupyter to mysql
insert_query='INSERT INTO before_handwashing_analysis VALUES'

In [138]:
Before_handwashing.shape

(76, 5)

In [139]:
for x in range(Before_handwashing.shape[0]):
    insert_query+='('
    for y in range(Before_handwashing.shape[1]):
        insert_query+=str(Before_handwashing[Before_handwashing.columns.values[y]][x])+', '
    insert_query=insert_query[:-2]+'), '

In [140]:
insert_query

'INSERT INTO before_handwashing_analysis VALUES(1841, 1, 254, 37, 0.14566929133858267), (1841, 2, 239, 18, 0.07531380753138076), (1841, 3, 277, 12, 0.04332129963898917), (1841, 4, 255, 4, 0.01568627450980392), (1841, 5, 255, 2, 0.00784313725490196), (1841, 6, 200, 10, 0.05), (1841, 7, 190, 16, 0.08421052631578947), (1841, 8, 222, 3, 0.013513513513513514), (1841, 9, 213, 4, 0.018779342723004695), (1841, 10, 236, 26, 0.11016949152542373), (1841, 11, 235, 53, 0.225531914893617), (1842, 1, 307, 64, 0.20846905537459284), (1842, 2, 311, 38, 0.12218649517684887), (1842, 3, 264, 27, 0.10227272727272728), (1842, 4, 242, 26, 0.10743801652892562), (1842, 5, 310, 10, 0.03225806451612903), (1842, 6, 273, 18, 0.06593406593406594), (1842, 7, 231, 48, 0.2077922077922078), (1842, 8, 216, 55, 0.25462962962962965), (1842, 9, 223, 41, 0.18385650224215247), (1842, 10, 242, 71, 0.29338842975206614), (1842, 11, 209, 48, 0.22966507177033493), (1842, 12, 239, 75, 0.3138075313807531), (1843, 1, 272, 52, 0.19117647058823528), (1843, 2, 263, 42, 0.1596958174904943), (1843, 3, 266, 33, 0.12406015037593984), (1843, 4, 285, 34, 0.11929824561403508), (1843, 5, 246, 15, 0.06097560975609756), (1843, 6, 196, 8, 0.04081632653061224), (1843, 7, 191, 1, 0.005235602094240838), (1843, 8, 193, 3, 0.015544041450777202), (1843, 9, 221, 5, 0.02262443438914027), (1843, 10, 250, 44, 0.176), (1843, 11, 252, 18, 0.07142857142857142), (1843, 12, 236, 19, 0.08050847457627118), (1844, 1, 244, 37, 0.15163934426229508), (1844, 2, 257, 29, 0.11284046692607004), (1844, 3, 276, 47, 0.17028985507246377), (1844, 4, 208, 36, 0.17307692307692307), (1844, 5, 240, 14, 0.058333333333333334), (1844, 6, 224, 6, 0.026785714285714284), (1844, 7, 206, 9, 0.043689320388349516), (1844, 8, 269, 17, 0.06319702602230483), (1844, 9, 245, 3, 0.012244897959183673), (1844, 10, 248, 8, 0.03225806451612903), (1844, 11, 245, 27, 0.11020408163265306), (1844, 12, 256, 27, 0.10546875), (1845, 1, 303, 23, 0.07590759075907591), (1845, 2, 274, 13, 0.04744525547445255), (1845, 3, 292, 13, 0.04452054794520548), (1845, 4, 260, 11, 0.04230769230769231), (1845, 5, 296, 13, 0.04391891891891892), (1845, 6, 280, 20, 0.07142857142857142), (1845, 7, 245, 15, 0.061224489795918366), (1845, 8, 251, 9, 0.035856573705179286), (1845, 9, 237, 25, 0.10548523206751055), (1845, 10, 283, 42, 0.14840989399293286), (1845, 11, 265, 29, 0.10943396226415095), (1845, 12, 267, 28, 0.10486891385767791), (1846, 1, 336, 45, 0.13392857142857142), (1846, 2, 293, 53, 0.18088737201365188), (1846, 3, 311, 48, 0.15434083601286175), (1846, 4, 253, 48, 0.18972332015810275), (1846, 5, 305, 41, 0.13442622950819672), (1846, 6, 266, 27, 0.10150375939849623), (1846, 7, 252, 33, 0.13095238095238096), (1846, 8, 216, 39, 0.18055555555555555), (1846, 9, 271, 39, 0.14391143911439114), (1846, 10, 254, 38, 0.14960629921259844), (1846, 11, 297, 32, 0.10774410774410774), (1846, 12, 298, 16, 0.053691275167785234), (1847, 1, 311, 10, 0.03215434083601286), (1847, 2, 312, 6, 0.019230769230769232), (1847, 3, 305, 11, 0.036065573770491806), (1847, 4, 312, 57, 0.18269230769230768), (1847, 5, 294, 36, 0.12244897959183673), '

In [141]:
insert_query=insert_query[:-2]+'; '

In [142]:
insert_query

'INSERT INTO before_handwashing_analysis VALUES(1841, 1, 254, 37, 0.14566929133858267), (1841, 2, 239, 18, 0.07531380753138076), (1841, 3, 277, 12, 0.04332129963898917), (1841, 4, 255, 4, 0.01568627450980392), (1841, 5, 255, 2, 0.00784313725490196), (1841, 6, 200, 10, 0.05), (1841, 7, 190, 16, 0.08421052631578947), (1841, 8, 222, 3, 0.013513513513513514), (1841, 9, 213, 4, 0.018779342723004695), (1841, 10, 236, 26, 0.11016949152542373), (1841, 11, 235, 53, 0.225531914893617), (1842, 1, 307, 64, 0.20846905537459284), (1842, 2, 311, 38, 0.12218649517684887), (1842, 3, 264, 27, 0.10227272727272728), (1842, 4, 242, 26, 0.10743801652892562), (1842, 5, 310, 10, 0.03225806451612903), (1842, 6, 273, 18, 0.06593406593406594), (1842, 7, 231, 48, 0.2077922077922078), (1842, 8, 216, 55, 0.25462962962962965), (1842, 9, 223, 41, 0.18385650224215247), (1842, 10, 242, 71, 0.29338842975206614), (1842, 11, 209, 48, 0.22966507177033493), (1842, 12, 239, 75, 0.3138075313807531), (1843, 1, 272, 52, 0.19117647058823528), (1843, 2, 263, 42, 0.1596958174904943), (1843, 3, 266, 33, 0.12406015037593984), (1843, 4, 285, 34, 0.11929824561403508), (1843, 5, 246, 15, 0.06097560975609756), (1843, 6, 196, 8, 0.04081632653061224), (1843, 7, 191, 1, 0.005235602094240838), (1843, 8, 193, 3, 0.015544041450777202), (1843, 9, 221, 5, 0.02262443438914027), (1843, 10, 250, 44, 0.176), (1843, 11, 252, 18, 0.07142857142857142), (1843, 12, 236, 19, 0.08050847457627118), (1844, 1, 244, 37, 0.15163934426229508), (1844, 2, 257, 29, 0.11284046692607004), (1844, 3, 276, 47, 0.17028985507246377), (1844, 4, 208, 36, 0.17307692307692307), (1844, 5, 240, 14, 0.058333333333333334), (1844, 6, 224, 6, 0.026785714285714284), (1844, 7, 206, 9, 0.043689320388349516), (1844, 8, 269, 17, 0.06319702602230483), (1844, 9, 245, 3, 0.012244897959183673), (1844, 10, 248, 8, 0.03225806451612903), (1844, 11, 245, 27, 0.11020408163265306), (1844, 12, 256, 27, 0.10546875), (1845, 1, 303, 23, 0.07590759075907591), (1845, 2, 274, 13, 0.04744525547445255), (1845, 3, 292, 13, 0.04452054794520548), (1845, 4, 260, 11, 0.04230769230769231), (1845, 5, 296, 13, 0.04391891891891892), (1845, 6, 280, 20, 0.07142857142857142), (1845, 7, 245, 15, 0.061224489795918366), (1845, 8, 251, 9, 0.035856573705179286), (1845, 9, 237, 25, 0.10548523206751055), (1845, 10, 283, 42, 0.14840989399293286), (1845, 11, 265, 29, 0.10943396226415095), (1845, 12, 267, 28, 0.10486891385767791), (1846, 1, 336, 45, 0.13392857142857142), (1846, 2, 293, 53, 0.18088737201365188), (1846, 3, 311, 48, 0.15434083601286175), (1846, 4, 253, 48, 0.18972332015810275), (1846, 5, 305, 41, 0.13442622950819672), (1846, 6, 266, 27, 0.10150375939849623), (1846, 7, 252, 33, 0.13095238095238096), (1846, 8, 216, 39, 0.18055555555555555), (1846, 9, 271, 39, 0.14391143911439114), (1846, 10, 254, 38, 0.14960629921259844), (1846, 11, 297, 32, 0.10774410774410774), (1846, 12, 298, 16, 0.053691275167785234), (1847, 1, 311, 10, 0.03215434083601286), (1847, 2, 312, 6, 0.019230769230769232), (1847, 3, 305, 11, 0.036065573770491806), (1847, 4, 312, 57, 0.18269230769230768), (1847, 5, 294, 36, 0.12244897959183673); '

In [143]:
cursor.execute(insert_query)

76

In [144]:
conn.commit()

In [145]:
conn.close()

In [146]:
conn=pymysql.connect(database='After_handwashing_analysis', user='root', password='22101989')

In [147]:
cursor=conn.cursor()

In [148]:
cursor.execute('select*from After_handwashing_analysis')

0

In [149]:
After_handwashig.shape

(22, 5)

In [172]:
insert_query='INSERT INTO After_handwashing_analysis VALUES'

In [151]:
After_handwashig.columns.values

array(['Year_v', 'Month_v', 'births', 'deaths', 'Proportions of death'],
      dtype=object)

In [152]:
#reseting the index of my second data set
After_handwashig.reset_index(drop=True, inplace=True)

In [162]:
After_handwashig

    Year_v  Month_v  births  deaths  Proportions of death
0     1847        6     268       6              0.022388
1     1847        7     250       3              0.012000
2     1847        8     264       5              0.018939
3     1847        9     262      12              0.045802
4     1847       10     278      11              0.039568
5     1847       11     246      11              0.044715
6     1847       12     273       8              0.029304
7     1848        1     283      10              0.035336
8     1848        2     291       2              0.006873
9     1848        3     276       0              0.000000
10    1848        4     305       2              0.006557
11    1848        5     313       3              0.009585
12    1848        6     264       3              0.011364
13    1848        7     269       1              0.003717
14    1848        8     261       0              0.000000
15    1848        9     312       3              0.009615
16    1848       10     299       7              0.023411
17    1848       11     310       9              0.029032
18    1848       12     373       5              0.013405
19    1849        1     403       9              0.022333
20    1849        2     389      12              0.030848
21    1849        3     406      20              0.049261

In [173]:
for x in range(After_handwashig.shape[0]):
    insert_query += '('
    for y in range(After_handwashig.shape[1]):
        insert_query += str(After_handwashig[After_handwashig.columns.values[y]][x]) + ', '
    insert_query = insert_query[:-2]+'), '

In [174]:
insert_query

'INSERT INTO After_handwashing_analysis VALUES(1847, 6, 268, 6, 0.022388059701492536), (1847, 7, 250, 3, 0.012), (1847, 8, 264, 5, 0.01893939393939394), (1847, 9, 262, 12, 0.04580152671755725), (1847, 10, 278, 11, 0.039568345323741004), (1847, 11, 246, 11, 0.044715447154471545), (1847, 12, 273, 8, 0.029304029304029304), (1848, 1, 283, 10, 0.0353356890459364), (1848, 2, 291, 2, 0.006872852233676976), (1848, 3, 276, 0, 0.0), (1848, 4, 305, 2, 0.006557377049180328), (1848, 5, 313, 3, 0.009584664536741214), (1848, 6, 264, 3, 0.011363636363636364), (1848, 7, 269, 1, 0.0037174721189591076), (1848, 8, 261, 0, 0.0), (1848, 9, 312, 3, 0.009615384615384616), (1848, 10, 299, 7, 0.023411371237458192), (1848, 11, 310, 9, 0.02903225806451613), (1848, 12, 373, 5, 0.013404825737265416), (1849, 1, 403, 9, 0.022332506203473945), (1849, 2, 389, 12, 0.030848329048843187), (1849, 3, 406, 20, 0.04926108374384237), '

In [175]:
insert_query=insert_query[:-2]+';'

In [176]:
insert_query

'INSERT INTO After_handwashing_analysis VALUES(1847, 6, 268, 6, 0.022388059701492536), (1847, 7, 250, 3, 0.012), (1847, 8, 264, 5, 0.01893939393939394), (1847, 9, 262, 12, 0.04580152671755725), (1847, 10, 278, 11, 0.039568345323741004), (1847, 11, 246, 11, 0.044715447154471545), (1847, 12, 273, 8, 0.029304029304029304), (1848, 1, 283, 10, 0.0353356890459364), (1848, 2, 291, 2, 0.006872852233676976), (1848, 3, 276, 0, 0.0), (1848, 4, 305, 2, 0.006557377049180328), (1848, 5, 313, 3, 0.009584664536741214), (1848, 6, 264, 3, 0.011363636363636364), (1848, 7, 269, 1, 0.0037174721189591076), (1848, 8, 261, 0, 0.0), (1848, 9, 312, 3, 0.009615384615384616), (1848, 10, 299, 7, 0.023411371237458192), (1848, 11, 310, 9, 0.02903225806451613), (1848, 12, 373, 5, 0.013404825737265416), (1849, 1, 403, 9, 0.022332506203473945), (1849, 2, 389, 12, 0.030848329048843187), (1849, 3, 406, 20, 0.04926108374384237);'

In [177]:
cursor.execute(insert_query)

22

In [178]:
conn.commit()

In [179]:
conn.close()